NatTypes.dfy(35,11): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    NatTypes.dfy(23,5): anon10_LoopHead
    (0,0): anon10_LoopBody
    NatTypes.dfy(23,5): anon11_Else
    (0,0): anon12_Then
NatTypes.dfy(10,4): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
NatTypes.dfy(43,13): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
NatTypes.dfy(45,13): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
NatTypes.dfy(62,15): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
NatTypes.dfy(76,15): Error: assertion violation
Execution trace:
    (0,0): anon0
    (0,0): anon5_Else
    (0,0): anon6_Then
NatTypes.dfy(97,21): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon3_Then
NatTypes.dfy(112,44): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon8_Else
    (0,0): anon9_Else
    (0,0): anon10_Then
NatTypes.dfy(135,34): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then

Dafny program verifier finished with 6 verified, 9 errors
